Repository cse110-fa21-group31/cse110-fa21-group31, pull requests merged in 2021-11, with the labels that each got.

#32 Edit page
  source/pages/editCreate.html
  source/scripts/editCreate.js
Labels: frontend

#39 skeleton of homepage
  source/pages/homePage.html
Labels: frontend

#38 made css for navbar and footer
  source/assets/styles/baseStyle.css
  source/cards/footer.html
  source/cards/navBar.html
Labels: frontend

#47 Meeting notes for 11/13 standup (frontend)
  .gitignore
  admin/.DS_Store
  admin/meetings/frontend/111321-standup.md
Labels: frontend

#41 Add Icons/Logos
  admin/branding/icons/Arrow.svg
  admin/branding/icons/Human.svg
  admin/branding/icons/deleterecipe.png
  admin/branding/icons/deleterecipe.svg
  admin/branding/icons/download.png
  admin/branding/icons/download.svg
  admin/branding/icons/editrecipe.png
  admin/branding/icons/editrecipe.svg
  admin/branding/icons/exit.png
  admin/branding/icons/exit.svg
  admin/branding/icons/minidelete.png
  admin/branding/icons/minidelete.svg
  admin/branding/icons/miniedit.png
  admin/branding/icons/miniedit.svg
  admin/branding/icons/miniplus.png
  admin/branding/icons/miniplus.svg
  admin/branding/icons/newrecipe.png
  admin/branding/icons/newrecipe.svg
  admin/branding/icons/olive.png
  admin/branding/icons/olive.svg
  admin/branding/icons/profile.png
  admin/branding/icons/profile.svg
  admin/branding/icons/save.png
  admin/branding/icons/save.svg
  admin/branding/icons/search.png
  admin/branding/icons/search.svg
  admin/branding/icons/settings.png
  admin/branding/icons/settings.svg
  admin/branding/icons/signout.png
  admin/branding/icons/signout.svg
  admin/branding/icons/signup.png
  admin/branding/icons/signup.svg
  admin/branding/icons/signup2.png
  admin/branding/icons/signup2.svg
  admin/branding/icons/upload.png
  admin/branding/icons/upload.svg
  admin/branding/logos/LogoMediumDark.png
  admin/branding/logos/LogoMediumLight.png
  admin/branding/logos/LogoSmallDark.png
  admin/branding/logos/LogoSmallLight.png
  source/pages/editCreate.html
Labels: enhancement, frontend

#50 Add class files
  source/scripts/profileClass.js
  source/scripts/recipeClass.js
Labels: enhancement, frontend

#61 Added css for recipe cards, index.html, some js on form submission
  index.html
  source/assets/Images/Olives-Computer-Wallpaper.jpg
  source/assets/styles/baseStyle.css
  source/assets/styles/cards.css
  source/cards/footer.html
  source/cards/navBar.html
  source/pages/accountSettings.html
  source/pages/editCreate.html
  source/pages/homePage.html
  source/pages/recipeDetail.html
  source/pages/userInfo.html
  source/scripts/indexSearch.js
Labels: frontend

#62 New pipeline/new workflows
  .codacy.yml
  .eslintrc.json
  .github/workflows/local-to-main.yml
  .github/workflows/main.yml
  .github/workflows/node.js.yml
  .gitignore
  .jshintignore
  .jshintrc
  __tests__/pipeline.spec.js
  cypress.json
  package-lock.json
  package.json
  source/scripts/example.js
  source/scripts/profileClass.js
Labels: enhancement

#66 Search API
  source/scripts/indexSearch.js
  source/service/neDB/interface.mjs
  source/service/neDB/server.mjs
Labels: backend, Database, search

#108 Nav Bar with Google
  index.html
  source/assets/styles/baseStyle.css
  source/assets/styles/cards.css
  source/cards/header.html
  source/cards/navBarWithGoogle.html
  source/pages/editCreate.html
  source/pages/homePage.html
  source/pages/login.html
  source/pages/recipeDetail.html
  source/pages/userInfo.html
  source/scripts/userInfo.js
  source/scripts/userLogin.js
  source/scripts/util.js
Labels: frontend

#120 detailCSS
  index.html
  source/assets/styles/baseStyle.css
  source/assets/styles/cards.css
  source/assets/styles/editCreate.css
  source/assets/styles/recipeDetail.css
  source/pages/editCreate.html
  source/pages/editPage.html
  source/pages/recipeDetail.html
  source/scripts/editPage.js
  source/scripts/recipeDetail.js
Labels: frontend

#122 New nav bar
  index.html
  source/assets/styles/baseStyle.css
  source/assets/styles/cards.css
  source/assets/styles/homePage.css
  source/scripts/index.js
  source/scripts/indexSearch.js
  source/scripts/userLogin.js
  source/service/.data/recipes
Labels: frontend
