Repository cse110-fa21-group31/cse110-fa21-group31, pull requests merged in 2021-12, with the labels that each got.

#142 Frontend meeting notes
  admin/meetings/frontend/112321-standup.md
  admin/meetings/frontend/113021-standup.md
Labels: frontend

#143 Lots of css changes
  .eslintignore
  index.html
  source/assets/styles/baseStyle.css
  source/assets/styles/cards.css
  source/assets/styles/editCreate.css
  source/assets/styles/homePage.css
  source/assets/styles/recipeDetail.css
  source/assets/styles/userInfo.css
  source/scripts/classes/recipeClass.js
  source/scripts/createPage.js
  source/scripts/editPage.js
  source/scripts/indexSearch.js
  source/scripts/userInfo.js
  source/service/.data/images/11
  source/service/.data/images/111
  source/service/.data/images/1111
  source/service/.data/images/11111
  source/service/.data/images/111111
  source/service/.data/images/1111111
  source/service/.data/images/11111111
  source/service/.data/images/111111111
  source/service/.data/images/1111111111
  source/service/.data/images/11111111111
  source/service/.data/images/111111111111
  source/service/.data/images/1111111111111
  source/service/.data/images/11111111111111
  source/service/.data/images/111111111111111
  source/service/.data/images/1111111111111111
  source/service/.data/images/11111111111111111
  source/service/.data/images/111111111111111111
  source/service/.data/images/1111111111111111111
  source/service/.data/images/11111111111111111111
  source/service/.data/images/111111111111111111111
  source/service/.data/images/1111111111111111111111
  source/service/.data/images/11111111111111111111111
  source/service/.data/images/111111111111111111111111
  source/service/.data/images/1111111111111111111111111
  source/service/.data/images/11111111111111111111111111
  source/service/.data/images/111111111111111111111111111
  source/service/.data/images/1111111111111111111111111111
  source/service/.data/images/11111111111111111111111111111
  source/service/.data/recipes
  source/service/server/jsons/10.json
Labels: bug, enhancement, frontend

#147 Fixed ingredients/steps adding and deleting, fixed edit page duplicat…
  __tests__/cypressAccountTests.spec.js
  __tests__/jestDBTests.test.js
  package.json
  source/scripts/createPage.js
  source/scripts/editPage.js
  source/service/.data/images/1
  source/service/.data/images/11
  source/service/.data/images/111
  source/service/.data/recipes
  source/service/.data/testrecipes
  source/service/.data/users
Labels: bug, frontend

#157 Save and Unsave Recipes
  index.html
  source/assets/Images/Empty_Heart.svg
  source/assets/Images/Filled_Heart.svg
  source/assets/styles/recipeDetail.css
  source/scripts/APICalls.js
  source/scripts/recipeDetail.js
  source/service/.data/users
Labels: backend, frontend, Database

#180 fix routing 404 when refresh
  source/scripts/index.js
  source/scripts/recipeDetail.js
  source/scripts/router/Router.js
  source/service/data/users
  source/service/server/fileRoutes.mjs
  source/service/server/server.mjs
Labels: enhancement

#188 Added tag category separation and changed HomePage css to landingTags
  index.html
  source/assets/styles/baseStyle.css
  source/assets/styles/homePage.css
  source/assets/styles/landingTags.css
  source/scripts/indexSearch.js
Labels: frontend

#141 Pipeline V3
  .github/workflows/local-to-main.yml
  __tests__/cypressAccountTests.spec.js
  __tests__/cypressE2ETests.spec.js
  __tests__/jestDBTests.test.js
  __tests__/testing.spec.js
  cypress.json
  cypress/plugins/index.cjs
  cypress/support/commands.js
  cypress/support/index.js
  index.html
  package-lock.json
  package.json
  source/scripts/APICalls.js
  source/scripts/classes/profileClass.js
  source/scripts/classes/recipeClass.js
  source/scripts/createPage.js
  source/scripts/disqus.js
  source/scripts/editPage.js
  source/scripts/index.js
  source/scripts/indexSearch.js
  source/scripts/recipeDetail.js
  source/scripts/router/Router.js
  source/scripts/userInfo.js
  source/scripts/userLogin.js
  source/scripts/util.js
  source/service/data/testrecipes
  source/service/util.js
  super-linter.log
Labels: enhancement

#194 Documentation for recipeClass.js and removed comments for userLogin.js
  source/scripts/classes/recipeClass.js
  source/scripts/userLogin.js
  source/service/.data/images/oSTEMConferenceFlyer.png
  source/service/data/recipes
  source/service/data/users
Labels: documentation
